--
-- Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

CREATE TABLE IF NOT EXISTS IDN_AUTH_REST_FLOW (
            FLOW_ID_IDENTIFIER VARCHAR (255) NOT NULL,
            FLOW_ID VARCHAR (255),
            FLOW_ID_STATE VARCHAR (25) DEFAULT 'ACTIVE',
            TIME_GENERATED LONG NOT NULL,
            EXPIRY_TIME LONG NOT NULL,
            IS_AUTH_FLOW_COMPLETED VARCHAR (10) DEFAULT 'FALSE',
            SP_APP_ID INTEGER,
            SP_TENANT_ID INTEGER DEFAULT -1,
            ORG_ID INTEGER DEFAULT 1,
            LOGGED_USER_CLAIM VARCHAR (255) NOT NULL,
            PRIMARY KEY (FLOW_ID_IDENTIFIER),
            CONSTRAINT FLOW_ID_CONSTRAINT UNIQUE (FLOW_ID),
            FOREIGN KEY (SP_APP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_REST_AUTH_USER (
            ID INTEGER AUTO_INCREMENT,
            USER_TENANT_ID INTEGER NOT NULL,
            USER_ID VARCHAR(255) NOT NULL,
            USERNAME VARCHAR(255) NOT NULL,
            FLOW_ID_IDENTIFIER VARCHAR (255) NOT NULL,
            PRIMARY KEY (ID),
            FOREIGN KEY (FLOW_ID_IDENTIFIER) REFERENCES IDN_AUTH_REST_FLOW(FLOW_ID_IDENTIFIER) ON DELETE CASCADE
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_REST_AUTH_AUTHENTICATED_STEPS (
            ID INTEGER AUTO_INCREMENT,
            DATA_KEY INTEGER NOT NULL,
            DATA_VALUE VARCHAR(85) NOT NULL,
            FLOW_ID_IDENTIFIER VARCHAR (255) NOT NULL,
            PRIMARY KEY (ID),
            CONSTRAINT AUTHENTICATED_STEPS_CONSTRAINT UNIQUE (DATA_KEY, DATA_VALUE, FLOW_ID_IDENTIFIER),
            FOREIGN KEY (FLOW_ID_IDENTIFIER) REFERENCES IDN_AUTH_REST_FLOW(FLOW_ID_IDENTIFIER) ON DELETE CASCADE
)ENGINE INNODB;

CREATE INDEX IDX_IDN_AUTH_REST_FLOW_ID ON IDN_AUTH_REST_FLOW(FLOW_ID);

CREATE INDEX IDX_REST_AUTH_AUTHENTICATED_STEPS_BY_FLOWID_IDENTIFIER ON IDN_REST_AUTH_AUTHENTICATED_STEPS(FLOW_ID_IDENTIFIER);

CREATE INDEX IDX_REST_AUTH_USER ON IDN_REST_AUTH_USER(FLOW_ID_IDENTIFIER);

CREATE INDEX IDX_IDN_AUTH_REST_FLOW_ID_AND_IDENTIFIER ON IDN_AUTH_REST_FLOW(FLOW_ID_IDENTIFIER,FLOW_ID);
