

DELIMITER //

CREATE PROCEDURE DeleteExpiredOrInactiveFlows()
BEGIN
    -- Delete from IDN_REST_AUTH_AUTHENTICATED_STEPS
    DELETE FROM IDN_REST_AUTH_AUTHENTICATED_STEPS
    WHERE FLOW_ID_IDENTIFIER IN (
        SELECT FLOW_ID_IDENTIFIER
        FROM IDN_AUTH_REST_FLOW
        WHERE FLOW_ID_STATE = 'EXPIRED' OR FLOW_ID_STATE = 'INACTIVE'
    );

    -- Delete from IDN_REST_AUTH_USER
    DELETE FROM IDN_REST_AUTH_USER
    WHERE FLOW_ID_IDENTIFIER IN (
        SELECT FLOW_ID_IDENTIFIER
        FROM IDN_AUTH_REST_FLOW
        WHERE FLOW_ID_STATE = 'EXPIRED' OR FLOW_ID_STATE = 'INACTIVE'
    );

    -- Delete from IDN_AUTH_REST_FLOW
    DELETE FROM IDN_AUTH_REST_FLOW
    WHERE FLOW_ID_STATE = 'EXPIRED' OR FLOW_ID_STATE = 'INACTIVE';
END //

DELIMITER ;