CREATE TABLE IDN_REST_AUTH_FLOW (
    FLOW_ID_IDENTIFIER VARCHAR(255) NOT NULL,
    FLOW_ID VARCHAR(255),
    FLOW_ID_STATE VARCHAR(25) DEFAULT 'ACTIVE',
    TIME_GENERATED BIGINT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    IS_AUTH_FLOW_COMPLETED VARCHAR(10) DEFAULT 'FALSE',
    SP_APP_ID INT,
    SP_TENANT_ID INT DEFAULT -1,
    ORG_ID INT DEFAULT 1,
    CONSTRAINT PK_IDN_REST_AUTH_FLOW PRIMARY KEY (FLOW_ID_IDENTIFIER),
    CONSTRAINT UK_IDN_REST_AUTH_FLOW_FLOW_ID UNIQUE (FLOW_ID),
    CONSTRAINT FK_IDN_REST_AUTH_FLOW_SP_APP FOREIGN KEY (SP_APP_ID) REFERENCES SP_APP(ID) ON DELETE CASCADE
);


CREATE TABLE IDN_REST_AUTH_USER (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_TENANT_ID INT NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    FLOW_ID_IDENTIFIER VARCHAR(255) NOT NULL,
    FOREIGN KEY (FLOW_ID_IDENTIFIER) REFERENCES IDN_REST_AUTH_FLOW(FLOW_ID_IDENTIFIER) ON DELETE CASCADE
);


CREATE TABLE IDN_REST_AUTH_AUTHENTICATED_STEPS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DATA_KEY INT NOT NULL,
    DATA_VALUE VARCHAR(85) NOT NULL,
    FLOW_ID_IDENTIFIER VARCHAR(255) NOT NULL,
    CONSTRAINT AUTHENTICATED_STEPS_CONSTRAINT UNIQUE (DATA_KEY, DATA_VALUE, FLOW_ID_IDENTIFIER),
    FOREIGN KEY (FLOW_ID_IDENTIFIER) REFERENCES IDN_REST_AUTH_FLOW (FLOW_ID_IDENTIFIER) ON DELETE CASCADE
);


CREATE PROCEDURE DeleteExpiredOrInactiveFlows
AS
BEGIN
    SET NOCOUNT ON;

    -- Delete from IDN_REST_AUTH_AUTHENTICATED_STEPS
    DELETE FROM IDN_REST_AUTH_AUTHENTICATED_STEPS
    WHERE FLOW_ID_IDENTIFIER IN (
        SELECT FLOW_ID_IDENTIFIER
        FROM IDN_REST_AUTH_FLOW
        WHERE FLOW_ID_STATE = 'EXPIRED' OR FLOW_ID_STATE = 'INACTIVE'
    );

    -- Delete from IDN_REST_AUTH_USER
    DELETE FROM IDN_REST_AUTH_USER
    WHERE FLOW_ID_IDENTIFIER IN (
        SELECT FLOW_ID_IDENTIFIER
        FROM IDN_REST_AUTH_FLOW
        WHERE FLOW_ID_STATE = 'EXPIRED' OR FLOW_ID_STATE = 'INACTIVE'
    );

    -- Delete from IDN_REST_AUTH_FLOW
    DELETE FROM IDN_REST_AUTH_FLOW
    WHERE FLOW_ID_STATE = 'EXPIRED' OR FLOW_ID_STATE = 'INACTIVE';

    SET NOCOUNT OFF;
END;
