package org.wso2.carbon.identity.oauth2.grant.mfa.framework.dao;

/**
 * MFA token related sql queries.
 */
public class SQLQueries {

    public static final String ADD_MFA_TOKEN_MYSQL = "INSERT INTO IDN_ETISALAT_AUTH_MFA_TOKEN (MFA_TOKEN_ID, " +
            "MFA_TOKEN, TOKEN_STATE, TIME_GENERATED, EXPIRY_TIME, IS_AUTH_FLOW_COMPLETED, SP_APP_ID, SP_TENANT_ID) " +
            "VALUES (?,?,?,?,?,?,?,?);";
    public static final String ADD_MFA_TOKEN_USER_DATA_MYSQL = "INSERT INTO IDN_ETISALAT_AUTH_USER " +
            "(USER_TENANT_ID, USER_ID, USERNAME, MFA_TOKEN_ID) VALUES (?,?,?,?);";
    public static final String UPDATE_MFA_TOKEN_STATE_MYSQL = "UPDATE IDN_ETISALAT_AUTH_MFA_TOKEN SET TOKEN_STATE=? " +
            "WHERE MFA_TOKEN=? ;";
    public static final String RETRIEVE_MFA_TOKEN_DATA_MYSQL = "SELECT MT.MFA_TOKEN_ID, MFA_TOKEN, TOKEN_STATE, " +
            "TIME_GENERATED, EXPIRY_TIME, IS_AUTH_FLOW_COMPLETED, SP_APP_ID, SP_TENANT_ID, USER_TENANT_ID, USER_ID, USERNAME FROM IDN_ETISALAT_AUTH_MFA_TOKEN AS MT INNER JOIN IDN_ETISALAT_AUTH_USER WHERE MFA_TOKEN =? ;";
    public static final String ADD_AUTHENTICATED_STEP_MYSQL = "INSERT INTO IDN_ETISALAT_AUTH_AUTHENTICATED_STEPS " +
            "(DATA_KEY, DATA_VALUE, MFA_TOKEN_ID) VALUES (?,?,?);";
    public static final String GET_AUTHENTICATED_STEPS_MYSQL = "SELECT DATA_KEY, DATA_VALUE FROM " +
            "IDN_ETISALAT_AUTH_AUTHENTICATED_STEPS WHERE MFA_TOKEN_ID = ?";
    public static final String UPDATE_AUTH_STEP_MFA_TOKEN_ID_MYSQL = "UPDATE IDN_ETISALAT_AUTH_AUTHENTICATED_STEPS " +
            "SET MFA_TOKEN_ID = ? WHERE MFA_TOKEN_ID = ?;";
    public static final String REFRESH_MFA_TOKEN_ID_MYSQL = "UPDATE IDN_ETISALAT_AUTH_USER AS MTU, " +
            "IDN_ETISALAT_AUTH_AUTHENTICATED_STEPS AS MTAS SET MTU.MFA_TOKEN_ID = ?, MTAS.MFA_TOKEN_ID = ? WHERE MTU" +
            ".MFA_TOKEN_ID = ? AND MTAS.MFA_TOKEN_ID = MTU.MFA_TOKEN_ID;";
}
